name: online_shopping_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Core & Firebase
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  firebase_database: ^12.1.0

  # Utilities
  fluttertoast: ^9.0.0
  shared_preferences: ^2.2.2
  intl: ^0.20.2

  # Media & Scanner
  image_picker: ^1.0.7
  mobile_scanner: ^7.1.4
  speech_to_text: ^7.0.0

  # Charts
  syncfusion_flutter_charts: ^31.2.18
  syncfusion_flutter_core: ^31.2.18

  # Cupertino icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Example for assets (optional)
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Example for fonts (optional)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
